### ISSUE TITLE
Can't chain with other commands

### ISSUE THREAD

**Issue by mwalz** [warapitiya/gulp-yarn#18]
Hello,

I believe I am missing something. I am trying to call `gulp-yarn` in my gulp file and then when it has completed I am attempting to zip the directory. `gulp-yarn` is not returning as expected. I have tried calling .on('end', callback) and a number of other techniques. 

Is there a stream or promise step I am missing when trying to do something like this:

```
gulp.task('default', ['dist-zip']);

gulp.task('build-modules', () => {
  return gulp.src(['./package.json', './yarn.lock'])
    .pipe(gulp.dest('./build'))
    .pipe(yarn({
      production: true
    }));
});

gulp.task('dist-zip', ['build-modules'], () => {
  return gulp.src(['./index.js', './build/**', '!./build/package.json', '!./build/yarn.lock'])
    .pipe(zip('lambda-function.zip'))
    .pipe(gulp.dest('dist'));
});
```

The use case is packaging things for an AWS Lambda function. We are trying to bundle only the files needed for Production. Yarn would run to create the node_modules directory, then some other steps before a zip file is created. Right now we can't get anything to happen after the `gulp-yarn` step.

Thanks,
Mark

**Comment by warapitiya** [comment]
@mwalz `gulp-yarn` only returns the package.json file since it's focusing only package.json file. Also the approach you trying to accomplice it not going to work since gulp run those task async.

You can solve this issue by following one approach from below 2.

### gulp 4
Upgrade to gulp 4 if you can, Gulp 4 provide serial & parallel methods to handle the task flow. [example](https://github.com/gulpjs/gulp/tree/4.0)

### npm script
Create 2 separate tasks in your gulp and run gulp tasks one after the other.

Example
```json
{
    "scripts": {
        "build": "gulp build && gulp zip"
    }
}
```

then run the command
```sh
yarn run build
```

**Comment by warapitiya** [comment]
@mwalz  I fixed this on v2.0.0-beta.3.

```sh
$ yarn add gulp-yarn@next
```

**Comment by onorok** [comment]
This still appears to not work for the .on('end', callback) method even in the latest v2.0.0-beta.3 build.  Giving me tons of headache today.
